# Generated by Django 4.2 on 2024-08-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Fantasma', 'Fantasma'), ('Fuego', 'Fuego'), ('Agua', 'Agua'), ('Tierra', 'Tierra')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='region',
            field=models.CharField(choices=[('Hoenn', 'Hoenn'), ('Unova', 'Unova'), ('Sinnoh', 'Sinnoh'), ('Paldea', 'Paldea'), ('Kanto', 'Kanto'), ('Kalos', 'Kalos'), ('Galar', 'Galar'), ('Alola', 'Alola'), ('Johto', 'Johto')], max_length=30),
        ),
    ]
