# Generated by Django 4.2 on 2024-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type_alter_trainer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Eléctrico', 'Eléctrico'), ('Planta', 'Planta'), ('Tierra', 'Tierra'), ('Fantasma', 'Fantasma'), ('Agua', 'Agua'), ('Fuego', 'Fuego')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='region',
            field=models.CharField(choices=[('Galar', 'Galar'), ('Sinnoh', 'Sinnoh'), ('Unova', 'Unova'), ('Paldea', 'Paldea'), ('Kalos', 'Kalos'), ('Hoenn', 'Hoenn'), ('Alola', 'Alola'), ('Johto', 'Johto'), ('Kanto', 'Kanto')], max_length=30),
        ),
    ]
