# Generated by Django 4.2 on 2024-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type_alter_trainer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', 'Fuego'), ('Fantasma', 'Fantasma'), ('Tierra', 'Tierra'), ('Agua', 'Agua'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='region',
            field=models.CharField(choices=[('Kanto', 'Kanto'), ('Sinnoh', 'Sinnoh'), ('Johto', 'Johto'), ('Kalos', 'Kalos'), ('Alola', 'Alola'), ('Unova', 'Unova'), ('Paldea', 'Paldea'), ('Hoenn', 'Hoenn'), ('Galar', 'Galar')], max_length=30),
        ),
    ]
